# Generated by Django 4.2.17 on 2025-01-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_masseuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the service category.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of the service category.', null=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Select the gender of the masseuse.', max_length=6),
        ),
        migrations.AlterField(
            model_name='masseuse',
            name='name',
            field=models.CharField(help_text="Enter the masseuse's name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Euro (€)', max_digits=6),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, help_text='Select the category this service belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.servicecategory'),
        ),
    ]
